import { UUID } from "crypto";

export declare interface Device {
  id: UUID;
  deviceId: string;
  name: string;
  customName: string;
  model: string;
  manufacturer: string;
  brand: string;
  serialNumber: string;
  operatingSystem: string;
  operatingSystemVersion: string;
  displayResolution: string;
  storageInGB: number;
  ramInGB: number;
  processor: string | null;
  batteryLevel: number;
  batteryInMah: number | null;
  firebaseToken: string | null;
  deviceType: string;
  appVersion: string;
  buildNumber: string;
  isTablet: boolean;
  isEmulator: boolean;
  ipAddress: string;
  timezone: string;
  deviceLocale: string;
  availableStorage: number;
  firstInstallTime: number;
  isCharging: boolean;
  apiLevel: number | null;
  loginCode: string | null;
  imei: string;
  macAddress: string;
  userId: UUID;
  locationId: UUID;
  departmentId: UUID | null;
  departmentName: string | null;
  canDelete: boolean;
  status: boolean;
  isArchived: boolean;
}
