import {boolean, object, string,} from "zod";

export const BusinessSchema= object({
    id: string().uuid().optional(),
    name: string().min(2, 'Business must be at least 2 characters').max(255, 'Business can not be more than 255 characters'),
    identificationNumber: string().nullable().optional(),
    certificateOfIncorporation: string().nullable().optional(),
    businessIdentificationDocument: string().nullable().optional(),
    businessLicense: string().nullable().optional(),
    memarts: string().nullable().optional(),
    description: string().optional().nullish(),
    vrn: string().nullable().optional(),
    serial: string().nullable().optional(),
    uin: string().nullable().optional(),
    businessType: string(),
    receiptPrefix: string().max(50).nullable().optional(),
    receiptSuffix: string().max(50).nullable().optional(),
    image: string().nullable().optional(),
    receiptImage: string().nullable().optional(),
    logo: string().nullable().optional(),
    notificationPhone: string().nullable().optional(),
    notificationEmailAddress: string({ message: "Notification email address is required" }).email({ message: "Invalid email address" }).optional(),
    website: string().nullish().optional(),
    facebook: string().nullish().optional(),
    instagram: string().nullish().optional(),
    twitter: string().nullish().optional(),
    linkedin: string().nullish().optional(),
    youtube: string().nullish().optional(),
    tiktok: string().nullish().optional(),
    country: string(),
    phoneNumber: string().optional(),
    email: string().optional(),
    address: string().optional(),
    vfdRegistrationState: boolean().optional(),
    status: boolean().optional(),
    primaryColor: string().max(20).nullable().optional(),
    secondaryColor: string().max(20).nullable().optional(),
    bannerImageUrl: string().max(500).nullable().optional(),
    faviconUrl: string().max(500).nullable().optional(),
    fontFamily: string().max(100).nullable().optional(),
    metaTitle: string().max(200).nullable().optional(),
    metaDescription: string().max(500).nullable().optional(),
    shareImageUrl: string().max(500).nullable().optional(),
})
