import {UUID} from "node:crypto";

export declare interface Business {
    id: UUID,
    prefix: string,
    name: string,
    tax: number,
    identificationNumber: string,
    vrn: string,
    serial: string,
    uin: string,
    receiptPrefix: string,
    receiptSuffix: string,
    businessType: string,
    slug: string,
    storeName: string,
    image: string,
    receiptImage: string,
    logo: string,
    facebook: string,
    twitter: string,
    instagram: string,
    linkedin: string,
    youtube: string,
    certificateOfIncorporation: string,
    businessIdentificationDocument: string,
    businessLicense: string,
    memarts: string,
    notificationPhone: string,
    notificationEmailAddress: string,
    description: string,
    vfdRegistrationState: boolean,
    website: string,
    canDelete: boolean,
    status: boolean,
    user: UUID,
    country: UUID,
    isArchived: boolean
}
